INSERT IGNORE INTO SyllabusTopics (Country,Subject,Level,Topic,SortOrder) VALUES

-- ============================================================
-- SINGAPORE PSLE — Mother Tongue (Chinese/Malay/Tamil), all compulsory
-- subjects that had zero coverage before this pass
-- ============================================================
('Singapore','Mother Tongue (Chinese)','Primary 1','Pinyin and Basic Characters',1),
('Singapore','Mother Tongue (Chinese)','Primary 1','Listening and Speaking',2),
('Singapore','Mother Tongue (Chinese)','Primary 1','Simple Sentences',3),
('Singapore','Mother Tongue (Chinese)','Primary 1','Character Recognition',4),
('Singapore','Mother Tongue (Chinese)','Primary 1','Basic Vocabulary',5),
('Singapore','Mother Tongue (Chinese)','Primary 1','Stroke Order and Writing',6),

('Singapore','Mother Tongue (Chinese)','Primary 2','Sentence Construction',1),
('Singapore','Mother Tongue (Chinese)','Primary 2','Reading Comprehension',2),
('Singapore','Mother Tongue (Chinese)','Primary 2','Vocabulary Expansion',3),
('Singapore','Mother Tongue (Chinese)','Primary 2','Guided Composition',4),
('Singapore','Mother Tongue (Chinese)','Primary 2','Oral Communication',5),
('Singapore','Mother Tongue (Chinese)','Primary 2','Character Writing',6),

('Singapore','Mother Tongue (Chinese)','Primary 3','Paragraph Writing',1),
('Singapore','Mother Tongue (Chinese)','Primary 3','Comprehension: Cloze Passage',2),
('Singapore','Mother Tongue (Chinese)','Primary 3','Idioms and Proverbs',3),
('Singapore','Mother Tongue (Chinese)','Primary 3','Oral: Reading Aloud',4),
('Singapore','Mother Tongue (Chinese)','Primary 3','Grammar Basics',5),
('Singapore','Mother Tongue (Chinese)','Primary 3','Listening Comprehension',6),

('Singapore','Mother Tongue (Chinese)','Primary 4','Composition Writing',1),
('Singapore','Mother Tongue (Chinese)','Primary 4','Comprehension: Open-ended',2),
('Singapore','Mother Tongue (Chinese)','Primary 4','Idioms and Proverbs',3),
('Singapore','Mother Tongue (Chinese)','Primary 4','Oral: Picture Discussion',4),
('Singapore','Mother Tongue (Chinese)','Primary 4','Grammar and Sentence Patterns',5),
('Singapore','Mother Tongue (Chinese)','Primary 4','Vocabulary Cloze',6),

('Singapore','Mother Tongue (Chinese)','Primary 5','Composition: Narrative Writing',1),
('Singapore','Mother Tongue (Chinese)','Primary 5','Comprehension: Inference',2),
('Singapore','Mother Tongue (Chinese)','Primary 5','Synthesis and Transformation',3),
('Singapore','Mother Tongue (Chinese)','Primary 5','Oral: Conversation',4),
('Singapore','Mother Tongue (Chinese)','Primary 5','Advanced Idioms and Proverbs',5),
('Singapore','Mother Tongue (Chinese)','Primary 5','Listening Comprehension',6),

('Singapore','Mother Tongue (Chinese)','Primary 6','PSLE Composition',1),
('Singapore','Mother Tongue (Chinese)','Primary 6','PSLE Comprehension',2),
('Singapore','Mother Tongue (Chinese)','Primary 6','Synthesis and Transformation',3),
('Singapore','Mother Tongue (Chinese)','Primary 6','Oral Examination Practice',4),
('Singapore','Mother Tongue (Chinese)','Primary 6','Vocabulary and Cloze',5),
('Singapore','Mother Tongue (Chinese)','Primary 6','PSLE Examination Strategies',6),

('Singapore','Mother Tongue (Malay)','Primary 1','Sebutan dan Suku Kata',1),
('Singapore','Mother Tongue (Malay)','Primary 1','Mendengar dan Bertutur',2),
('Singapore','Mother Tongue (Malay)','Primary 1','Ayat Mudah',3),
('Singapore','Mother Tongue (Malay)','Primary 1','Kosa Kata Asas',4),
('Singapore','Mother Tongue (Malay)','Primary 1','Membaca Awal',5),
('Singapore','Mother Tongue (Malay)','Primary 1','Tulisan Awal',6),

('Singapore','Mother Tongue (Malay)','Primary 2','Penulisan Ayat',1),
('Singapore','Mother Tongue (Malay)','Primary 2','Pemahaman Bacaan',2),
('Singapore','Mother Tongue (Malay)','Primary 2','Kosa Kata',3),
('Singapore','Mother Tongue (Malay)','Primary 2','Karangan Berpandu',4),
('Singapore','Mother Tongue (Malay)','Primary 2','Lisan',5),
('Singapore','Mother Tongue (Malay)','Primary 2','Ejaan',6),

('Singapore','Mother Tongue (Malay)','Primary 3','Karangan Pendek',1),
('Singapore','Mother Tongue (Malay)','Primary 3','Pemahaman Petikan',2),
('Singapore','Mother Tongue (Malay)','Primary 3','Peribahasa Asas',3),
('Singapore','Mother Tongue (Malay)','Primary 3','Lisan: Bacaan Kuat',4),
('Singapore','Mother Tongue (Malay)','Primary 3','Tatabahasa Asas',5),
('Singapore','Mother Tongue (Malay)','Primary 3','Kefahaman Mendengar',6),

('Singapore','Mother Tongue (Malay)','Primary 4','Karangan',1),
('Singapore','Mother Tongue (Malay)','Primary 4','Pemahaman Terbuka',2),
('Singapore','Mother Tongue (Malay)','Primary 4','Peribahasa dan Simpulan Bahasa',3),
('Singapore','Mother Tongue (Malay)','Primary 4','Lisan: Perbincangan Gambar',4),
('Singapore','Mother Tongue (Malay)','Primary 4','Tatabahasa',5),
('Singapore','Mother Tongue (Malay)','Primary 4','Kosa Kata Kloz',6),

('Singapore','Mother Tongue (Malay)','Primary 5','Karangan Naratif',1),
('Singapore','Mother Tongue (Malay)','Primary 5','Pemahaman: Inferens',2),
('Singapore','Mother Tongue (Malay)','Primary 5','Sintesis dan Transformasi',3),
('Singapore','Mother Tongue (Malay)','Primary 5','Lisan: Perbualan',4),
('Singapore','Mother Tongue (Malay)','Primary 5','Peribahasa Lanjutan',5),
('Singapore','Mother Tongue (Malay)','Primary 5','Kefahaman Mendengar',6),

('Singapore','Mother Tongue (Malay)','Primary 6','Karangan PSLE',1),
('Singapore','Mother Tongue (Malay)','Primary 6','Pemahaman PSLE',2),
('Singapore','Mother Tongue (Malay)','Primary 6','Sintesis dan Transformasi',3),
('Singapore','Mother Tongue (Malay)','Primary 6','Lisan PSLE',4),
('Singapore','Mother Tongue (Malay)','Primary 6','Kosa Kata dan Kloz',5),
('Singapore','Mother Tongue (Malay)','Primary 6','Strategi Peperiksaan PSLE',6),

('Singapore','Mother Tongue (Tamil)','Primary 1','Basic Letters and Sounds',1),
('Singapore','Mother Tongue (Tamil)','Primary 1','Listening and Speaking',2),
('Singapore','Mother Tongue (Tamil)','Primary 1','Simple Sentences',3),
('Singapore','Mother Tongue (Tamil)','Primary 1','Basic Vocabulary',4),
('Singapore','Mother Tongue (Tamil)','Primary 1','Early Reading',5),
('Singapore','Mother Tongue (Tamil)','Primary 1','Early Writing',6),

('Singapore','Mother Tongue (Tamil)','Primary 2','Sentence Writing',1),
('Singapore','Mother Tongue (Tamil)','Primary 2','Reading Comprehension',2),
('Singapore','Mother Tongue (Tamil)','Primary 2','Vocabulary Building',3),
('Singapore','Mother Tongue (Tamil)','Primary 2','Guided Composition',4),
('Singapore','Mother Tongue (Tamil)','Primary 2','Oral Skills',5),
('Singapore','Mother Tongue (Tamil)','Primary 2','Spelling',6),

('Singapore','Mother Tongue (Tamil)','Primary 3','Short Composition',1),
('Singapore','Mother Tongue (Tamil)','Primary 3','Comprehension Passages',2),
('Singapore','Mother Tongue (Tamil)','Primary 3','Basic Idioms',3),
('Singapore','Mother Tongue (Tamil)','Primary 3','Oral: Reading Aloud',4),
('Singapore','Mother Tongue (Tamil)','Primary 3','Basic Grammar',5),
('Singapore','Mother Tongue (Tamil)','Primary 3','Listening Comprehension',6),

('Singapore','Mother Tongue (Tamil)','Primary 4','Composition Writing',1),
('Singapore','Mother Tongue (Tamil)','Primary 4','Comprehension: Open-ended',2),
('Singapore','Mother Tongue (Tamil)','Primary 4','Idioms and Proverbs',3),
('Singapore','Mother Tongue (Tamil)','Primary 4','Oral: Picture Discussion',4),
('Singapore','Mother Tongue (Tamil)','Primary 4','Grammar',5),
('Singapore','Mother Tongue (Tamil)','Primary 4','Vocabulary Cloze',6),

('Singapore','Mother Tongue (Tamil)','Primary 5','Narrative Composition',1),
('Singapore','Mother Tongue (Tamil)','Primary 5','Comprehension: Inference',2),
('Singapore','Mother Tongue (Tamil)','Primary 5','Synthesis and Transformation',3),
('Singapore','Mother Tongue (Tamil)','Primary 5','Oral: Conversation',4),
('Singapore','Mother Tongue (Tamil)','Primary 5','Advanced Idioms',5),
('Singapore','Mother Tongue (Tamil)','Primary 5','Listening Comprehension',6),

('Singapore','Mother Tongue (Tamil)','Primary 6','PSLE Composition',1),
('Singapore','Mother Tongue (Tamil)','Primary 6','PSLE Comprehension',2),
('Singapore','Mother Tongue (Tamil)','Primary 6','Synthesis and Transformation',3),
('Singapore','Mother Tongue (Tamil)','Primary 6','Oral Examination Practice',4),
('Singapore','Mother Tongue (Tamil)','Primary 6','Vocabulary and Cloze',5),
('Singapore','Mother Tongue (Tamil)','Primary 6','PSLE Examination Strategies',6),

-- ============================================================
-- SINGAPORE PSLE — Science gap fill (Primary 1-2; P3-6 already seeded)
-- ============================================================
('Singapore','Science','Primary 1','Observing My Surroundings',1),
('Singapore','Science','Primary 1','Living and Non-living Things',2),
('Singapore','Science','Primary 1','My Five Senses',3),
('Singapore','Science','Primary 1','Plants Around Us',4),
('Singapore','Science','Primary 1','Animals Around Us',5),
('Singapore','Science','Primary 1','Simple Science Tools',6),

('Singapore','Science','Primary 2','Plant and Animal Needs',1),
('Singapore','Science','Primary 2','Materials and their Uses',2),
('Singapore','Science','Primary 2','Push and Pull',3),
('Singapore','Science','Primary 2','Light and Shadows',4),
('Singapore','Science','Primary 2','Simple Measurement',5),
('Singapore','Science','Primary 2','Caring for the Environment',6),

-- ============================================================
-- SINGAPORE N/O-LEVEL — Mother Tongue (Chinese/Malay/Tamil), Secondary 1-5
-- ============================================================
('Singapore','Mother Tongue (Chinese)','Secondary 1','Comprehension: Inference',1),
('Singapore','Mother Tongue (Chinese)','Secondary 1','Composition Writing',2),
('Singapore','Mother Tongue (Chinese)','Secondary 1','Grammar and Sentence Patterns',3),
('Singapore','Mother Tongue (Chinese)','Secondary 1','Idioms and Proverbs',4),
('Singapore','Mother Tongue (Chinese)','Secondary 1','Oral Communication',5),
('Singapore','Mother Tongue (Chinese)','Secondary 1','Listening Comprehension',6),

('Singapore','Mother Tongue (Chinese)','Secondary 2','Comprehension: Evaluation',1),
('Singapore','Mother Tongue (Chinese)','Secondary 2','Argumentative Writing',2),
('Singapore','Mother Tongue (Chinese)','Secondary 2','Grammar and Editing',3),
('Singapore','Mother Tongue (Chinese)','Secondary 2','Idioms and Proverbs',4),
('Singapore','Mother Tongue (Chinese)','Secondary 2','Oral: Stimulus Discussion',5),
('Singapore','Mother Tongue (Chinese)','Secondary 2','Summary Writing',6),

('Singapore','Mother Tongue (Chinese)','Secondary 3','Comprehension: Extended Response',1),
('Singapore','Mother Tongue (Chinese)','Secondary 3','Composition: Argumentative',2),
('Singapore','Mother Tongue (Chinese)','Secondary 3','Summary Writing',3),
('Singapore','Mother Tongue (Chinese)','Secondary 3','Grammar and Editing',4),
('Singapore','Mother Tongue (Chinese)','Secondary 3','Oral: Reading and Discussion',5),
('Singapore','Mother Tongue (Chinese)','Secondary 3','Listening Comprehension',6),

('Singapore','Mother Tongue (Chinese)','Secondary 4','O-Level Comprehension',1),
('Singapore','Mother Tongue (Chinese)','Secondary 4','O-Level Composition',2),
('Singapore','Mother Tongue (Chinese)','Secondary 4','Summary Writing',3),
('Singapore','Mother Tongue (Chinese)','Secondary 4','Grammar and Editing',4),
('Singapore','Mother Tongue (Chinese)','Secondary 4','Oral Examination Practice',5),
('Singapore','Mother Tongue (Chinese)','Secondary 4','Listening Examination Practice',6),

('Singapore','Mother Tongue (Chinese)','Secondary 5','N-Level Comprehension',1),
('Singapore','Mother Tongue (Chinese)','Secondary 5','N-Level Composition',2),
('Singapore','Mother Tongue (Chinese)','Secondary 5','Summary Writing',3),
('Singapore','Mother Tongue (Chinese)','Secondary 5','Grammar and Editing',4),
('Singapore','Mother Tongue (Chinese)','Secondary 5','Oral Examination Practice',5),
('Singapore','Mother Tongue (Chinese)','Secondary 5','Examination Strategies',6),

('Singapore','Mother Tongue (Malay)','Secondary 1','Pemahaman: Inferens',1),
('Singapore','Mother Tongue (Malay)','Secondary 1','Penulisan Karangan',2),
('Singapore','Mother Tongue (Malay)','Secondary 1','Tatabahasa',3),
('Singapore','Mother Tongue (Malay)','Secondary 1','Peribahasa dan Simpulan Bahasa',4),
('Singapore','Mother Tongue (Malay)','Secondary 1','Lisan',5),
('Singapore','Mother Tongue (Malay)','Secondary 1','Kefahaman Mendengar',6),

('Singapore','Mother Tongue (Malay)','Secondary 2','Pemahaman: Penilaian',1),
('Singapore','Mother Tongue (Malay)','Secondary 2','Karangan Hujah',2),
('Singapore','Mother Tongue (Malay)','Secondary 2','Tatabahasa dan Penyuntingan',3),
('Singapore','Mother Tongue (Malay)','Secondary 2','Peribahasa',4),
('Singapore','Mother Tongue (Malay)','Secondary 2','Lisan: Perbincangan',5),
('Singapore','Mother Tongue (Malay)','Secondary 2','Ringkasan',6),

('Singapore','Mother Tongue (Malay)','Secondary 3','Pemahaman Lanjutan',1),
('Singapore','Mother Tongue (Malay)','Secondary 3','Karangan Hujah',2),
('Singapore','Mother Tongue (Malay)','Secondary 3','Ringkasan',3),
('Singapore','Mother Tongue (Malay)','Secondary 3','Tatabahasa dan Penyuntingan',4),
('Singapore','Mother Tongue (Malay)','Secondary 3','Lisan: Bacaan dan Perbincangan',5),
('Singapore','Mother Tongue (Malay)','Secondary 3','Kefahaman Mendengar',6),

('Singapore','Mother Tongue (Malay)','Secondary 4','Pemahaman O-Level',1),
('Singapore','Mother Tongue (Malay)','Secondary 4','Karangan O-Level',2),
('Singapore','Mother Tongue (Malay)','Secondary 4','Ringkasan',3),
('Singapore','Mother Tongue (Malay)','Secondary 4','Tatabahasa dan Penyuntingan',4),
('Singapore','Mother Tongue (Malay)','Secondary 4','Lisan',5),
('Singapore','Mother Tongue (Malay)','Secondary 4','Kefahaman Mendengar',6),

('Singapore','Mother Tongue (Malay)','Secondary 5','Pemahaman N-Level',1),
('Singapore','Mother Tongue (Malay)','Secondary 5','Karangan N-Level',2),
('Singapore','Mother Tongue (Malay)','Secondary 5','Ringkasan',3),
('Singapore','Mother Tongue (Malay)','Secondary 5','Tatabahasa',4),
('Singapore','Mother Tongue (Malay)','Secondary 5','Lisan',5),
('Singapore','Mother Tongue (Malay)','Secondary 5','Strategi Peperiksaan',6),

('Singapore','Mother Tongue (Tamil)','Secondary 1','Comprehension: Inference',1),
('Singapore','Mother Tongue (Tamil)','Secondary 1','Composition Writing',2),
('Singapore','Mother Tongue (Tamil)','Secondary 1','Grammar',3),
('Singapore','Mother Tongue (Tamil)','Secondary 1','Idioms and Proverbs',4),
('Singapore','Mother Tongue (Tamil)','Secondary 1','Oral Communication',5),
('Singapore','Mother Tongue (Tamil)','Secondary 1','Listening Comprehension',6),

('Singapore','Mother Tongue (Tamil)','Secondary 2','Comprehension: Evaluation',1),
('Singapore','Mother Tongue (Tamil)','Secondary 2','Argumentative Writing',2),
('Singapore','Mother Tongue (Tamil)','Secondary 2','Grammar and Editing',3),
('Singapore','Mother Tongue (Tamil)','Secondary 2','Idioms and Proverbs',4),
('Singapore','Mother Tongue (Tamil)','Secondary 2','Oral: Stimulus Discussion',5),
('Singapore','Mother Tongue (Tamil)','Secondary 2','Summary Writing',6),

('Singapore','Mother Tongue (Tamil)','Secondary 3','Comprehension: Extended Response',1),
('Singapore','Mother Tongue (Tamil)','Secondary 3','Composition: Argumentative',2),
('Singapore','Mother Tongue (Tamil)','Secondary 3','Summary Writing',3),
('Singapore','Mother Tongue (Tamil)','Secondary 3','Grammar and Editing',4),
('Singapore','Mother Tongue (Tamil)','Secondary 3','Oral: Reading and Discussion',5),
('Singapore','Mother Tongue (Tamil)','Secondary 3','Listening Comprehension',6),

('Singapore','Mother Tongue (Tamil)','Secondary 4','O-Level Comprehension',1),
('Singapore','Mother Tongue (Tamil)','Secondary 4','O-Level Composition',2),
('Singapore','Mother Tongue (Tamil)','Secondary 4','Summary Writing',3),
('Singapore','Mother Tongue (Tamil)','Secondary 4','Grammar and Editing',4),
('Singapore','Mother Tongue (Tamil)','Secondary 4','Oral Examination Practice',5),
('Singapore','Mother Tongue (Tamil)','Secondary 4','Listening Examination Practice',6),

('Singapore','Mother Tongue (Tamil)','Secondary 5','N-Level Comprehension',1),
('Singapore','Mother Tongue (Tamil)','Secondary 5','N-Level Composition',2),
('Singapore','Mother Tongue (Tamil)','Secondary 5','Summary Writing',3),
('Singapore','Mother Tongue (Tamil)','Secondary 5','Grammar and Editing',4),
('Singapore','Mother Tongue (Tamil)','Secondary 5','Oral Examination Practice',5),
('Singapore','Mother Tongue (Tamil)','Secondary 5','Examination Strategies',6),

-- ============================================================
-- SINGAPORE N/O-LEVEL — remaining electives, Secondary 1-5
-- ============================================================
('Singapore','Combined Science','Secondary 1','Introduction to Science Practical Skills',1),
('Singapore','Combined Science','Secondary 1','Cell Structure',2),
('Singapore','Combined Science','Secondary 1','States of Matter',3),
('Singapore','Combined Science','Secondary 1','Forces and Motion',4),
('Singapore','Combined Science','Secondary 1','Energy',5),
('Singapore','Combined Science','Secondary 1','Simple Chemical Reactions',6),

('Singapore','Combined Science','Secondary 2','Nutrition and Digestion',1),
('Singapore','Combined Science','Secondary 2','Respiration',2),
('Singapore','Combined Science','Secondary 2','The Periodic Table',3),
('Singapore','Combined Science','Secondary 2','Acids Bases and Salts',4),
('Singapore','Combined Science','Secondary 2','Electricity Basics',5),
('Singapore','Combined Science','Secondary 2','Light and Sound',6),

('Singapore','Combined Science','Secondary 3','Chemical Bonding',1),
('Singapore','Combined Science','Secondary 3','Reproduction in Humans',2),
('Singapore','Combined Science','Secondary 3','Forces and Pressure',3),
('Singapore','Combined Science','Secondary 3','Electromagnetism',4),
('Singapore','Combined Science','Secondary 3','Ecosystems',5),
('Singapore','Combined Science','Secondary 3','Rate of Reaction',6),

('Singapore','Combined Science','Secondary 4','Organic Chemistry Basics',1),
('Singapore','Combined Science','Secondary 4','Genetics and Inheritance',2),
('Singapore','Combined Science','Secondary 4','Electricity and Circuits',3),
('Singapore','Combined Science','Secondary 4','Waves',4),
('Singapore','Combined Science','Secondary 4','Redox Reactions',5),
('Singapore','Combined Science','Secondary 4','O-Level Examination Preparation',6),

('Singapore','Combined Science','Secondary 5','Revision: Chemistry Core Topics',1),
('Singapore','Combined Science','Secondary 5','Revision: Physics Core Topics',2),
('Singapore','Combined Science','Secondary 5','Revision: Biology Core Topics',3),
('Singapore','Combined Science','Secondary 5','Practical Skills Revision',4),
('Singapore','Combined Science','Secondary 5','N-Level Examination Preparation',5),
('Singapore','Combined Science','Secondary 5','Examination Strategies',6),

('Singapore','Social Studies','Secondary 1','Living in a Diverse Society',1),
('Singapore','Social Studies','Secondary 1','Singapore''s Governance',2),
('Singapore','Social Studies','Secondary 1','Source-based Skills',3),
('Singapore','Social Studies','Secondary 1','Citizenship and Identity',4),
('Singapore','Social Studies','Secondary 1','Managing Diversity',5),
('Singapore','Social Studies','Secondary 1','Case Studies',6),

('Singapore','Social Studies','Secondary 2','Being Global and Being Singaporean',1),
('Singapore','Social Studies','Secondary 2','Riot and Reconciliation Case Study',2),
('Singapore','Social Studies','Secondary 2','Source-based Skills',3),
('Singapore','Social Studies','Secondary 2','Globalisation Issues',4),
('Singapore','Social Studies','Secondary 2','Media Literacy',5),
('Singapore','Social Studies','Secondary 2','Case Studies',6),

('Singapore','Social Studies','Secondary 3','Governance and Society',1),
('Singapore','Social Studies','Secondary 3','Global Issues',2),
('Singapore','Social Studies','Secondary 3','Source-based Case Study',3),
('Singapore','Social Studies','Secondary 3','Response Question Skills',4),
('Singapore','Social Studies','Secondary 3','Issue Analysis',5),
('Singapore','Social Studies','Secondary 3','Essay Writing Skills',6),

('Singapore','Social Studies','Secondary 4','O-Level SBQ Practice',1),
('Singapore','Social Studies','Secondary 4','O-Level Response Question Practice',2),
('Singapore','Social Studies','Secondary 4','Case Study Revision',3),
('Singapore','Social Studies','Secondary 4','Issue Analysis',4),
('Singapore','Social Studies','Secondary 4','Source Evaluation Skills',5),
('Singapore','Social Studies','Secondary 4','Examination Preparation',6),

('Singapore','Social Studies','Secondary 5','N-Level SBQ Practice',1),
('Singapore','Social Studies','Secondary 5','N-Level Response Question Practice',2),
('Singapore','Social Studies','Secondary 5','Case Study Revision',3),
('Singapore','Social Studies','Secondary 5','Issue Analysis',4),
('Singapore','Social Studies','Secondary 5','Source Evaluation Skills',5),
('Singapore','Social Studies','Secondary 5','Examination Strategies',6),

('Singapore','Literature in English','Secondary 1','Introduction to Poetry',1),
('Singapore','Literature in English','Secondary 1','Introduction to Prose',2),
('Singapore','Literature in English','Secondary 1','Introduction to Drama',3),
('Singapore','Literature in English','Secondary 1','Literary Devices',4),
('Singapore','Literature in English','Secondary 1','Character Analysis',5),
('Singapore','Literature in English','Secondary 1','Response Writing',6),

('Singapore','Literature in English','Secondary 2','Poetry Analysis',1),
('Singapore','Literature in English','Secondary 2','Prose Analysis',2),
('Singapore','Literature in English','Secondary 2','Drama Analysis',3),
('Singapore','Literature in English','Secondary 2','Themes and Context',4),
('Singapore','Literature in English','Secondary 2','Character Analysis',5),
('Singapore','Literature in English','Secondary 2','Essay Writing',6),

('Singapore','Literature in English','Secondary 3','Set Text: Poetry',1),
('Singapore','Literature in English','Secondary 3','Set Text: Prose',2),
('Singapore','Literature in English','Secondary 3','Set Text: Drama',3),
('Singapore','Literature in English','Secondary 3','Unseen Poetry',4),
('Singapore','Literature in English','Secondary 3','Unseen Prose',5),
('Singapore','Literature in English','Secondary 3','Essay Writing Skills',6),

('Singapore','Literature in English','Secondary 4','O-Level Set Text Revision',1),
('Singapore','Literature in English','Secondary 4','Unseen Poetry Practice',2),
('Singapore','Literature in English','Secondary 4','Unseen Prose Practice',3),
('Singapore','Literature in English','Secondary 4','Essay Writing Practice',4),
('Singapore','Literature in English','Secondary 4','Critical Analysis',5),
('Singapore','Literature in English','Secondary 4','Examination Preparation',6),

('Singapore','Literature in English','Secondary 5','N-Level Set Text Revision',1),
('Singapore','Literature in English','Secondary 5','Unseen Poetry Practice',2),
('Singapore','Literature in English','Secondary 5','Unseen Prose Practice',3),
('Singapore','Literature in English','Secondary 5','Essay Writing Practice',4),
('Singapore','Literature in English','Secondary 5','Critical Analysis',5),
('Singapore','Literature in English','Secondary 5','Examination Strategies',6),

('Singapore','Computing','Secondary 1','Introduction to Computational Thinking',1),
('Singapore','Computing','Secondary 1','Basic Programming Concepts',2),
('Singapore','Computing','Secondary 1','Data Representation',3),
('Singapore','Computing','Secondary 1','Simple Algorithms',4),
('Singapore','Computing','Secondary 1','Introduction to the Internet',5),
('Singapore','Computing','Secondary 1','Digital Citizenship',6),

('Singapore','Computing','Secondary 2','Programming: Sequence and Selection',1),
('Singapore','Computing','Secondary 2','Programming: Iteration',2),
('Singapore','Computing','Secondary 2','Data Structures Basics',3),
('Singapore','Computing','Secondary 2','Networks Basics',4),
('Singapore','Computing','Secondary 2','Databases Basics',5),
('Singapore','Computing','Secondary 2','Project Work',6),

('Singapore','Computing','Secondary 3','Algorithms and Flowcharts',1),
('Singapore','Computing','Secondary 3','Object-Oriented Programming Basics',2),
('Singapore','Computing','Secondary 3','Data Structures',3),
('Singapore','Computing','Secondary 3','Computer Systems',4),
('Singapore','Computing','Secondary 3','Networks and Security',5),
('Singapore','Computing','Secondary 3','Project Work',6),

('Singapore','Computing','Secondary 4','Programming Practice',1),
('Singapore','Computing','Secondary 4','Data Structures and Algorithms',2),
('Singapore','Computing','Secondary 4','Databases',3),
('Singapore','Computing','Secondary 4','Computer Systems and Networks',4),
('Singapore','Computing','Secondary 4','School-based Coursework',5),
('Singapore','Computing','Secondary 4','O-Level Examination Preparation',6),

('Singapore','Computing','Secondary 5','Programming Practice',1),
('Singapore','Computing','Secondary 5','Data Structures and Algorithms',2),
('Singapore','Computing','Secondary 5','Databases',3),
('Singapore','Computing','Secondary 5','Computer Systems and Networks',4),
('Singapore','Computing','Secondary 5','School-based Coursework',5),
('Singapore','Computing','Secondary 5','Examination Preparation',6),

('Singapore','Art','Secondary 1','Elements of Art',1),
('Singapore','Art','Secondary 1','Drawing Techniques',2),
('Singapore','Art','Secondary 1','Colour Theory',3),
('Singapore','Art','Secondary 1','Painting Techniques',4),
('Singapore','Art','Secondary 1','Art Appreciation',5),
('Singapore','Art','Secondary 1','Sketchbook Development',6),

('Singapore','Art','Secondary 2','Composition and Design',1),
('Singapore','Art','Secondary 2','Printmaking',2),
('Singapore','Art','Secondary 2','Sculpture Basics',3),
('Singapore','Art','Secondary 2','Mixed Media',4),
('Singapore','Art','Secondary 2','Art History Survey',5),
('Singapore','Art','Secondary 2','Sketchbook Development',6),

('Singapore','Art','Secondary 3','Observational Drawing',1),
('Singapore','Art','Secondary 3','Personal Art Themes',2),
('Singapore','Art','Secondary 3','Digital Art Basics',3),
('Singapore','Art','Secondary 3','Critical Studies',4),
('Singapore','Art','Secondary 3','Coursework Development',5),
('Singapore','Art','Secondary 3','Artist Research',6),

('Singapore','Art','Secondary 4','Coursework Refinement',1),
('Singapore','Art','Secondary 4','Exam Theme Development',2),
('Singapore','Art','Secondary 4','Critical Studies',3),
('Singapore','Art','Secondary 4','Portfolio Presentation',4),
('Singapore','Art','Secondary 4','Artist Research',5),
('Singapore','Art','Secondary 4','O-Level Examination Preparation',6),

('Singapore','Art','Secondary 5','Coursework Refinement',1),
('Singapore','Art','Secondary 5','Exam Theme Development',2),
('Singapore','Art','Secondary 5','Critical Studies',3),
('Singapore','Art','Secondary 5','Portfolio Presentation',4),
('Singapore','Art','Secondary 5','Artist Research',5),
('Singapore','Art','Secondary 5','Examination Preparation',6),

('Singapore','Music','Secondary 1','Music Theory Basics',1),
('Singapore','Music','Secondary 1','Rhythm and Notation',2),
('Singapore','Music','Secondary 1','Listening Skills',3),
('Singapore','Music','Secondary 1','Basic Performance Skills',4),
('Singapore','Music','Secondary 1','Composition Basics',5),
('Singapore','Music','Secondary 1','Music Appreciation',6),

('Singapore','Music','Secondary 2','Intermediate Music Theory',1),
('Singapore','Music','Secondary 2','Ensemble Performance',2),
('Singapore','Music','Secondary 2','Listening and Analysis',3),
('Singapore','Music','Secondary 2','Composition Techniques',4),
('Singapore','Music','Secondary 2','World Music Styles',5),
('Singapore','Music','Secondary 2','Music Appreciation',6),

('Singapore','Music','Secondary 3','Advanced Music Theory',1),
('Singapore','Music','Secondary 3','Performance Practice',2),
('Singapore','Music','Secondary 3','Score Analysis',3),
('Singapore','Music','Secondary 3','Composition Coursework',4),
('Singapore','Music','Secondary 3','Music History Survey',5),
('Singapore','Music','Secondary 3','Aural Skills',6),

('Singapore','Music','Secondary 4','Coursework Refinement',1),
('Singapore','Music','Secondary 4','Performance Assessment Preparation',2),
('Singapore','Music','Secondary 4','Score Analysis',3),
('Singapore','Music','Secondary 4','Composition Refinement',4),
('Singapore','Music','Secondary 4','Aural Skills',5),
('Singapore','Music','Secondary 4','O-Level Examination Preparation',6),

('Singapore','Music','Secondary 5','Coursework Refinement',1),
('Singapore','Music','Secondary 5','Performance Assessment Preparation',2),
('Singapore','Music','Secondary 5','Score Analysis',3),
('Singapore','Music','Secondary 5','Composition Refinement',4),
('Singapore','Music','Secondary 5','Aural Skills',5),
('Singapore','Music','Secondary 5','Examination Preparation',6),

('Singapore','Design & Technology','Secondary 1','Design Process Basics',1),
('Singapore','Design & Technology','Secondary 1','Sketching and Drawing',2),
('Singapore','Design & Technology','Secondary 1','Materials and Tools',3),
('Singapore','Design & Technology','Secondary 1','Simple Mechanisms',4),
('Singapore','Design & Technology','Secondary 1','Model Making',5),
('Singapore','Design & Technology','Secondary 1','Design Evaluation',6),

('Singapore','Design & Technology','Secondary 2','Design Briefs and Specifications',1),
('Singapore','Design & Technology','Secondary 2','Technical Drawing',2),
('Singapore','Design & Technology','Secondary 2','Materials Properties',3),
('Singapore','Design & Technology','Secondary 2','Structures and Mechanisms',4),
('Singapore','Design & Technology','Secondary 2','Prototyping',5),
('Singapore','Design & Technology','Secondary 2','Design Evaluation',6),

('Singapore','Design & Technology','Secondary 3','Design Thinking Process',1),
('Singapore','Design & Technology','Secondary 3','CAD Basics',2),
('Singapore','Design & Technology','Secondary 3','Materials Selection',3),
('Singapore','Design & Technology','Secondary 3','Systems and Control',4),
('Singapore','Design & Technology','Secondary 3','Coursework Development',5),
('Singapore','Design & Technology','Secondary 3','Design Evaluation',6),

('Singapore','Design & Technology','Secondary 4','Coursework Refinement',1),
('Singapore','Design & Technology','Secondary 4','Design Folio Development',2),
('Singapore','Design & Technology','Secondary 4','Prototyping and Testing',3),
('Singapore','Design & Technology','Secondary 4','Systems and Control',4),
('Singapore','Design & Technology','Secondary 4','Design Evaluation',5),
('Singapore','Design & Technology','Secondary 4','O-Level Examination Preparation',6),

('Singapore','Design & Technology','Secondary 5','Coursework Refinement',1),
('Singapore','Design & Technology','Secondary 5','Design Folio Development',2),
('Singapore','Design & Technology','Secondary 5','Prototyping and Testing',3),
('Singapore','Design & Technology','Secondary 5','Systems and Control',4),
('Singapore','Design & Technology','Secondary 5','Design Evaluation',5),
('Singapore','Design & Technology','Secondary 5','Examination Preparation',6),

('Singapore','Food & Nutrition','Secondary 1','Food Safety and Hygiene',1),
('Singapore','Food & Nutrition','Secondary 1','Basic Nutrition',2),
('Singapore','Food & Nutrition','Secondary 1','Kitchen Tools and Equipment',3),
('Singapore','Food & Nutrition','Secondary 1','Basic Cooking Methods',4),
('Singapore','Food & Nutrition','Secondary 1','Meal Planning Basics',5),
('Singapore','Food & Nutrition','Secondary 1','Food Presentation',6),

('Singapore','Food & Nutrition','Secondary 2','Nutrients and Diet',1),
('Singapore','Food & Nutrition','Secondary 2','Food Preparation Techniques',2),
('Singapore','Food & Nutrition','Secondary 2','Special Dietary Needs',3),
('Singapore','Food & Nutrition','Secondary 2','Recipe Modification',4),
('Singapore','Food & Nutrition','Secondary 2','Food Costing',5),
('Singapore','Food & Nutrition','Secondary 2','Food Presentation',6),

('Singapore','Food & Nutrition','Secondary 3','Nutrition Across the Lifespan',1),
('Singapore','Food & Nutrition','Secondary 3','Advanced Cooking Techniques',2),
('Singapore','Food & Nutrition','Secondary 3','Food Science Basics',3),
('Singapore','Food & Nutrition','Secondary 3','Menu Planning',4),
('Singapore','Food & Nutrition','Secondary 3','Coursework Development',5),
('Singapore','Food & Nutrition','Secondary 3','Food Presentation',6),

('Singapore','Food & Nutrition','Secondary 4','Coursework Refinement',1),
('Singapore','Food & Nutrition','Secondary 4','Practical Examination Preparation',2),
('Singapore','Food & Nutrition','Secondary 4','Menu Planning',3),
('Singapore','Food & Nutrition','Secondary 4','Food Science',4),
('Singapore','Food & Nutrition','Secondary 4','Written Paper Revision',5),
('Singapore','Food & Nutrition','Secondary 4','O-Level Examination Preparation',6),

('Singapore','Food & Nutrition','Secondary 5','Coursework Refinement',1),
('Singapore','Food & Nutrition','Secondary 5','Practical Examination Preparation',2),
('Singapore','Food & Nutrition','Secondary 5','Menu Planning',3),
('Singapore','Food & Nutrition','Secondary 5','Food Science',4),
('Singapore','Food & Nutrition','Secondary 5','Written Paper Revision',5),
('Singapore','Food & Nutrition','Secondary 5','Examination Preparation',6),

-- ============================================================
-- SINGAPORE N/O-LEVEL — Secondary 5 fill for existing core subjects
-- ============================================================
('Singapore','English Language','Secondary 5','N-Level Comprehension',1),
('Singapore','English Language','Secondary 5','N-Level Composition',2),
('Singapore','English Language','Secondary 5','Summary Writing',3),
('Singapore','English Language','Secondary 5','Grammar and Editing',4),
('Singapore','English Language','Secondary 5','Oral: Reading Aloud and Conversation',5),
('Singapore','English Language','Secondary 5','Examination Strategies',6),

('Singapore','Mathematics','Secondary 5','Numbers and Algebra Revision',1),
('Singapore','Mathematics','Secondary 5','Geometry and Mensuration Revision',2),
('Singapore','Mathematics','Secondary 5','Statistics Revision',3),
('Singapore','Mathematics','Secondary 5','Graphs and Functions',4),
('Singapore','Mathematics','Secondary 5','Problem Solving Practice',5),
('Singapore','Mathematics','Secondary 5','N-Level Examination Preparation',6),

('Singapore','Additional Mathematics','Secondary 5','Algebra Revision',1),
('Singapore','Additional Mathematics','Secondary 5','Trigonometry Revision',2),
('Singapore','Additional Mathematics','Secondary 5','Calculus Revision',3),
('Singapore','Additional Mathematics','Secondary 5','Coordinate Geometry Revision',4),
('Singapore','Additional Mathematics','Secondary 5','Problem Solving Practice',5),
('Singapore','Additional Mathematics','Secondary 5','Examination Preparation',6),

('Singapore','Physics','Secondary 5','Mechanics Revision',1),
('Singapore','Physics','Secondary 5','Thermal Physics Revision',2),
('Singapore','Physics','Secondary 5','Waves and Optics Revision',3),
('Singapore','Physics','Secondary 5','Electricity and Magnetism Revision',4),
('Singapore','Physics','Secondary 5','Practical Skills Revision',5),
('Singapore','Physics','Secondary 5','N-Level Examination Preparation',6),

('Singapore','Chemistry','Secondary 5','Particulate Nature of Matter Revision',1),
('Singapore','Chemistry','Secondary 5','Acids Bases and Salts Revision',2),
('Singapore','Chemistry','Secondary 5','The Periodic Table Revision',3),
('Singapore','Chemistry','Secondary 5','Organic Chemistry Revision',4),
('Singapore','Chemistry','Secondary 5','Practical Skills Revision',5),
('Singapore','Chemistry','Secondary 5','N-Level Examination Preparation',6),

('Singapore','Biology','Secondary 5','Cells and Nutrition Revision',1),
('Singapore','Biology','Secondary 5','Transport and Respiration Revision',2),
('Singapore','Biology','Secondary 5','Homeostasis and Reproduction Revision',3),
('Singapore','Biology','Secondary 5','Genetics and Evolution Revision',4),
('Singapore','Biology','Secondary 5','Practical Skills Revision',5),
('Singapore','Biology','Secondary 5','N-Level Examination Preparation',6),

('Singapore','History','Secondary 5','Source-based Skills Revision',1),
('Singapore','History','Secondary 5','Essay Writing Practice',2),
('Singapore','History','Secondary 5','Case Study Revision',3),
('Singapore','History','Secondary 5','Timeline and Key Events Review',4),
('Singapore','History','Secondary 5','Practice Questions',5),
('Singapore','History','Secondary 5','Examination Strategies',6),

('Singapore','Geography','Secondary 5','Physical Geography Revision',1),
('Singapore','Geography','Secondary 5','Human Geography Revision',2),
('Singapore','Geography','Secondary 5','Skills Paper Practice',3),
('Singapore','Geography','Secondary 5','Case Study Revision',4),
('Singapore','Geography','Secondary 5','Fieldwork Skills',5),
('Singapore','Geography','Secondary 5','Examination Strategies',6),

('Singapore','Principles of Accounts','Secondary 5','Bookkeeping Revision',1),
('Singapore','Principles of Accounts','Secondary 5','Financial Statements Revision',2),
('Singapore','Principles of Accounts','Secondary 5','Adjustments Revision',3),
('Singapore','Principles of Accounts','Secondary 5','Ratio Analysis',4),
('Singapore','Principles of Accounts','Secondary 5','Practice Questions',5),
('Singapore','Principles of Accounts','Secondary 5','Examination Preparation',6),

-- ============================================================
-- SINGAPORE A-LEVEL — remaining JC electives
-- ============================================================
('Singapore','H2 Further Mathematics','JC1','Complex Numbers',1),
('Singapore','H2 Further Mathematics','JC1','Matrices and Linear Spaces',2),
('Singapore','H2 Further Mathematics','JC1','Further Calculus',3),
('Singapore','H2 Further Mathematics','JC1','Graphing Techniques',4),
('Singapore','H2 Further Mathematics','JC1','Further Vectors',5),
('Singapore','H2 Further Mathematics','JC1','Mathematical Induction',6),

('Singapore','H2 Further Mathematics','JC2','Further Differential Equations',1),
('Singapore','H2 Further Mathematics','JC2','Numerical Methods',2),
('Singapore','H2 Further Mathematics','JC2','Further Probability',3),
('Singapore','H2 Further Mathematics','JC2','Further Statistics',4),
('Singapore','H2 Further Mathematics','JC2','Group Theory Basics',5),
('Singapore','H2 Further Mathematics','JC2','A-Level Examination Preparation',6),

('Singapore','H2 History','JC1','Historiography and Source Skills',1),
('Singapore','H2 History','JC1','The Cold War',2),
('Singapore','H2 History','JC1','Emergence of a Bipolar World',3),
('Singapore','H2 History','JC1','Search for Peace and Security',4),
('Singapore','H2 History','JC1','Essay Writing Skills',5),
('Singapore','H2 History','JC1','Document-based Question Skills',6),

('Singapore','H2 History','JC2','Regional Conflicts and Cooperation',1),
('Singapore','H2 History','JC2','Development of Southeast Asia',2),
('Singapore','H2 History','JC2','A-Level Essay Practice',3),
('Singapore','H2 History','JC2','A-Level DBQ Practice',4),
('Singapore','H2 History','JC2','Case Studies',5),
('Singapore','H2 History','JC2','Examination Strategies',6),

('Singapore','H2 Geography','JC1','Tropical Environments',1),
('Singapore','H2 Geography','JC1','Climatic Change',2),
('Singapore','H2 Geography','JC1','Geographical Skills',3),
('Singapore','H2 Geography','JC1','Fieldwork Techniques',4),
('Singapore','H2 Geography','JC1','Case Studies',5),
('Singapore','H2 Geography','JC1','Essay Writing Skills',6),

('Singapore','H2 Geography','JC2','Development Geography',1),
('Singapore','H2 Geography','JC2','Global Interactions',2),
('Singapore','H2 Geography','JC2','A-Level Essay Practice',3),
('Singapore','H2 Geography','JC2','A-Level Data Response Practice',4),
('Singapore','H2 Geography','JC2','Case Studies',5),
('Singapore','H2 Geography','JC2','Examination Strategies',6),

('Singapore','H2 Literature in English','JC1','Poetry Analysis',1),
('Singapore','H2 Literature in English','JC1','Prose Analysis',2),
('Singapore','H2 Literature in English','JC1','Drama Analysis',3),
('Singapore','H2 Literature in English','JC1','Literary Criticism Basics',4),
('Singapore','H2 Literature in English','JC1','Set Text Study',5),
('Singapore','H2 Literature in English','JC1','Essay Writing Skills',6),

('Singapore','H2 Literature in English','JC2','Comparative Analysis',1),
('Singapore','H2 Literature in English','JC2','Unseen Poetry Practice',2),
('Singapore','H2 Literature in English','JC2','Unseen Prose Practice',3),
('Singapore','H2 Literature in English','JC2','A-Level Essay Practice',4),
('Singapore','H2 Literature in English','JC2','Set Text Revision',5),
('Singapore','H2 Literature in English','JC2','Examination Strategies',6),

('Singapore','H1 Project Work','JC1','Group Project Skills',1),
('Singapore','H1 Project Work','JC1','Research and Planning',2),
('Singapore','H1 Project Work','JC1','Written Report Skills',3),
('Singapore','H1 Project Work','JC1','Oral Presentation Skills',4),
('Singapore','H1 Project Work','JC1','Group Interaction Skills',5),
('Singapore','H1 Project Work','JC1','Assessment Criteria Overview',6),

('Singapore','H1 Project Work','JC2','Report Refinement',1),
('Singapore','H1 Project Work','JC2','Presentation Refinement',2),
('Singapore','H1 Project Work','JC2','Group Interaction Practice',3),
('Singapore','H1 Project Work','JC2','Q&A Preparation',4),
('Singapore','H1 Project Work','JC2','Mock Assessment Practice',5),
('Singapore','H1 Project Work','JC2','Examination Preparation',6),

-- ============================================================
-- MALAYSIA UPSR — History elective, Primary 1-6
-- ============================================================
('Malaysia','History','Primary 1','My Family History',1),
('Malaysia','History','Primary 1','My Community',2),
('Malaysia','History','Primary 1','Important Places Nearby',3),
('Malaysia','History','Primary 1','Simple Timelines',4),
('Malaysia','History','Primary 1','National Symbols',5),
('Malaysia','History','Primary 1','Stories from the Past',6),

('Malaysia','History','Primary 2','Our Local Heritage',1),
('Malaysia','History','Primary 2','Early Settlements',2),
('Malaysia','History','Primary 2','National Symbols and Days',3),
('Malaysia','History','Primary 2','Simple Timelines',4),
('Malaysia','History','Primary 2','Community Leaders',5),
('Malaysia','History','Primary 2','Stories from the Past',6),

('Malaysia','History','Primary 3','Early Malay Kingdoms',1),
('Malaysia','History','Primary 3','Trade and Early Contacts',2),
('Malaysia','History','Primary 3','Local Historical Figures',3),
('Malaysia','History','Primary 3','Historical Sources',4),
('Malaysia','History','Primary 3','National Identity',5),
('Malaysia','History','Primary 3','Timeline Skills',6),

('Malaysia','History','Primary 4','Malacca Sultanate',1),
('Malaysia','History','Primary 4','Colonial Arrival',2),
('Malaysia','History','Primary 4','Historical Figures',3),
('Malaysia','History','Primary 4','Historical Sources',4),
('Malaysia','History','Primary 4','National Identity',5),
('Malaysia','History','Primary 4','Timeline Skills',6),

('Malaysia','History','Primary 5','Colonisation of Malaya',1),
('Malaysia','History','Primary 5','Japanese Occupation Overview',2),
('Malaysia','History','Primary 5','Path to Independence',3),
('Malaysia','History','Primary 5','Historical Sources',4),
('Malaysia','History','Primary 5','National Identity',5),
('Malaysia','History','Primary 5','UPSR Preparation',6),

('Malaysia','History','Primary 6','Formation of Malaysia',1),
('Malaysia','History','Primary 6','Nation Building',2),
('Malaysia','History','Primary 6','Key Historical Figures',3),
('Malaysia','History','Primary 6','Historical Sources',4),
('Malaysia','History','Primary 6','National Identity',5),
('Malaysia','History','Primary 6','UPSR Examination Preparation',6),

-- ============================================================
-- MALAYSIA UPSR — Science gap fill (Primary 1-2; P3-6 already seeded)
-- ============================================================
('Malaysia','Science','Primary 1','Observing My Surroundings',1),
('Malaysia','Science','Primary 1','Living and Non-living Things',2),
('Malaysia','Science','Primary 1','My Five Senses',3),
('Malaysia','Science','Primary 1','Plants Around Us',4),
('Malaysia','Science','Primary 1','Animals Around Us',5),
('Malaysia','Science','Primary 1','Simple Science Tools',6),

('Malaysia','Science','Primary 2','Plant and Animal Needs',1),
('Malaysia','Science','Primary 2','Materials and their Uses',2),
('Malaysia','Science','Primary 2','Push and Pull',3),
('Malaysia','Science','Primary 2','Light and Shadows',4),
('Malaysia','Science','Primary 2','Simple Measurement',5),
('Malaysia','Science','Primary 2','Caring for the Environment',6),

-- ============================================================
-- MALAYSIA PT3 — remaining electives, Form 1-3
-- ============================================================
('Malaysia','Islamic Education','Form 1','Aqidah Basics',1),
('Malaysia','Islamic Education','Form 1','Ibadah Fundamentals',2),
('Malaysia','Islamic Education','Form 1','Seerah of the Prophet',3),
('Malaysia','Islamic Education','Form 1','Akhlak and Adab',4),
('Malaysia','Islamic Education','Form 1','Al-Quran Recitation',5),
('Malaysia','Islamic Education','Form 1','Basic Fiqh',6),

('Malaysia','Islamic Education','Form 2','Aqidah: Pillars of Faith',1),
('Malaysia','Islamic Education','Form 2','Ibadah: Fasting and Zakat',2),
('Malaysia','Islamic Education','Form 2','Seerah: Madinah Period',3),
('Malaysia','Islamic Education','Form 2','Akhlak in Daily Life',4),
('Malaysia','Islamic Education','Form 2','Al-Quran Tajwid',5),
('Malaysia','Islamic Education','Form 2','Fiqh: Muamalat Basics',6),

('Malaysia','Islamic Education','Form 3','Aqidah: Advanced Topics',1),
('Malaysia','Islamic Education','Form 3','Ibadah: Hajj',2),
('Malaysia','Islamic Education','Form 3','Islamic History Overview',3),
('Malaysia','Islamic Education','Form 3','Akhlak and Character Building',4),
('Malaysia','Islamic Education','Form 3','Al-Quran and Hadith Study',5),
('Malaysia','Islamic Education','Form 3','PT3 Preparation',6),

('Malaysia','Moral Education','Form 1','Core Moral Values',1),
('Malaysia','Moral Education','Form 1','Self and Family Values',2),
('Malaysia','Moral Education','Form 1','Values in the Community',3),
('Malaysia','Moral Education','Form 1','Case Study Discussions',4),
('Malaysia','Moral Education','Form 1','Values and the Environment',5),
('Malaysia','Moral Education','Form 1','Reflective Writing',6),

('Malaysia','Moral Education','Form 2','Values in Society',1),
('Malaysia','Moral Education','Form 2','National Values',2),
('Malaysia','Moral Education','Form 2','Values and Human Rights',3),
('Malaysia','Moral Education','Form 2','Case Study Discussions',4),
('Malaysia','Moral Education','Form 2','Values and Technology',5),
('Malaysia','Moral Education','Form 2','Reflective Writing',6),

('Malaysia','Moral Education','Form 3','Values and Global Citizenship',1),
('Malaysia','Moral Education','Form 3','Values in Governance',2),
('Malaysia','Moral Education','Form 3','Case Study Discussions',3),
('Malaysia','Moral Education','Form 3','Values and Sustainability',4),
('Malaysia','Moral Education','Form 3','Ethical Decision Making',5),
('Malaysia','Moral Education','Form 3','PT3 Preparation',6),

('Malaysia','Design & Technology','Form 1','Design Process Basics',1),
('Malaysia','Design & Technology','Form 1','Sketching and Drawing',2),
('Malaysia','Design & Technology','Form 1','Materials and Tools',3),
('Malaysia','Design & Technology','Form 1','Simple Mechanisms',4),
('Malaysia','Design & Technology','Form 1','Model Making',5),
('Malaysia','Design & Technology','Form 1','Design Evaluation',6),

('Malaysia','Design & Technology','Form 2','Design Briefs and Specifications',1),
('Malaysia','Design & Technology','Form 2','Technical Drawing',2),
('Malaysia','Design & Technology','Form 2','Materials Properties',3),
('Malaysia','Design & Technology','Form 2','Structures and Mechanisms',4),
('Malaysia','Design & Technology','Form 2','Prototyping',5),
('Malaysia','Design & Technology','Form 2','Design Evaluation',6),

('Malaysia','Design & Technology','Form 3','Design Thinking Process',1),
('Malaysia','Design & Technology','Form 3','Materials Selection',2),
('Malaysia','Design & Technology','Form 3','Systems and Control',3),
('Malaysia','Design & Technology','Form 3','Coursework Development',4),
('Malaysia','Design & Technology','Form 3','Design Evaluation',5),
('Malaysia','Design & Technology','Form 3','PT3 Preparation',6),

-- ============================================================
-- MALAYSIA SPM — remaining electives, Form 4-5
-- ============================================================
('Malaysia','Commerce','Form 4','Introduction to Commerce',1),
('Malaysia','Commerce','Form 4','Business Organisations',2),
('Malaysia','Commerce','Form 4','Banking Services',3),
('Malaysia','Commerce','Form 4','Insurance Basics',4),
('Malaysia','Commerce','Form 4','Trade and Transport',5),
('Malaysia','Commerce','Form 4','Consumer Protection',6),

('Malaysia','Commerce','Form 5','International Trade',1),
('Malaysia','Commerce','Form 5','E-Commerce',2),
('Malaysia','Commerce','Form 5','Marketing Basics',3),
('Malaysia','Commerce','Form 5','Warehousing and Distribution',4),
('Malaysia','Commerce','Form 5','Practice Questions',5),
('Malaysia','Commerce','Form 5','SPM Examination Preparation',6),

('Malaysia','Business Studies','Form 4','Introduction to Business',1),
('Malaysia','Business Studies','Form 4','Forms of Business Ownership',2),
('Malaysia','Business Studies','Form 4','Business Planning',3),
('Malaysia','Business Studies','Form 4','Marketing Concepts',4),
('Malaysia','Business Studies','Form 4','Human Resource Basics',5),
('Malaysia','Business Studies','Form 4','Business Ethics',6),

('Malaysia','Business Studies','Form 5','Operations Management',1),
('Malaysia','Business Studies','Form 5','Financial Management Basics',2),
('Malaysia','Business Studies','Form 5','Entrepreneurship',3),
('Malaysia','Business Studies','Form 5','Business Growth Strategies',4),
('Malaysia','Business Studies','Form 5','Practice Questions',5),
('Malaysia','Business Studies','Form 5','SPM Examination Preparation',6),

('Malaysia','Information Technology','Form 4','Computer Systems Basics',1),
('Malaysia','Information Technology','Form 4','Programming Fundamentals',2),
('Malaysia','Information Technology','Form 4','Data Representation',3),
('Malaysia','Information Technology','Form 4','Networks Basics',4),
('Malaysia','Information Technology','Form 4','Databases Basics',5),
('Malaysia','Information Technology','Form 4','ICT and Society',6),

('Malaysia','Information Technology','Form 5','Programming Practice',1),
('Malaysia','Information Technology','Form 5','Data Structures',2),
('Malaysia','Information Technology','Form 5','Networks and Security',3),
('Malaysia','Information Technology','Form 5','Databases',4),
('Malaysia','Information Technology','Form 5','Project Work',5),
('Malaysia','Information Technology','Form 5','SPM Examination Preparation',6),

('Malaysia','Moral Education','Form 4','Values and Nationhood',1),
('Malaysia','Moral Education','Form 4','Values and Ethics',2),
('Malaysia','Moral Education','Form 4','Case Study Discussions',3),
('Malaysia','Moral Education','Form 4','Values and Global Issues',4),
('Malaysia','Moral Education','Form 4','Reflective Writing',5),
('Malaysia','Moral Education','Form 4','Essay Writing Skills',6),

('Malaysia','Moral Education','Form 5','Values and Leadership',1),
('Malaysia','Moral Education','Form 5','Values and Sustainability',2),
('Malaysia','Moral Education','Form 5','Case Study Discussions',3),
('Malaysia','Moral Education','Form 5','Ethical Decision Making',4),
('Malaysia','Moral Education','Form 5','Practice Questions',5),
('Malaysia','Moral Education','Form 5','SPM Examination Preparation',6),

('Malaysia','Islamic Studies','Form 4','Aqidah: Advanced Topics',1),
('Malaysia','Islamic Studies','Form 4','Fiqh: Muamalat',2),
('Malaysia','Islamic Studies','Form 4','Seerah and Islamic History',3),
('Malaysia','Islamic Studies','Form 4','Al-Quran and Tafsir',4),
('Malaysia','Islamic Studies','Form 4','Hadith Studies',5),
('Malaysia','Islamic Studies','Form 4','Akhlak and Character',6),

('Malaysia','Islamic Studies','Form 5','Fiqh: Munakahat',1),
('Malaysia','Islamic Studies','Form 5','Islamic Civilisation',2),
('Malaysia','Islamic Studies','Form 5','Al-Quran and Tafsir',3),
('Malaysia','Islamic Studies','Form 5','Hadith Studies',4),
('Malaysia','Islamic Studies','Form 5','Practice Questions',5),
('Malaysia','Islamic Studies','Form 5','SPM Examination Preparation',6),

('Malaysia','Art & Design','Form 4','Elements and Principles of Design',1),
('Malaysia','Art & Design','Form 4','Drawing and Illustration',2),
('Malaysia','Art & Design','Form 4','Colour and Composition',3),
('Malaysia','Art & Design','Form 4','Traditional Malaysian Art Forms',4),
('Malaysia','Art & Design','Form 4','Coursework Development',5),
('Malaysia','Art & Design','Form 4','Critique and Appreciation',6),

('Malaysia','Art & Design','Form 5','Coursework Refinement',1),
('Malaysia','Art & Design','Form 5','Portfolio Development',2),
('Malaysia','Art & Design','Form 5','Critical Studies',3),
('Malaysia','Art & Design','Form 5','Artist Research',4),
('Malaysia','Art & Design','Form 5','Practice Questions',5),
('Malaysia','Art & Design','Form 5','SPM Examination Preparation',6),

-- ============================================================
-- MALAYSIA STPM — remaining electives, Lower Six/Upper Six
-- ============================================================
('Malaysia','Further Mathematics (T)','Lower Six','Complex Numbers',1),
('Malaysia','Further Mathematics (T)','Lower Six','Matrices and Linear Spaces',2),
('Malaysia','Further Mathematics (T)','Lower Six','Further Calculus',3),
('Malaysia','Further Mathematics (T)','Lower Six','Graphing Techniques',4),
('Malaysia','Further Mathematics (T)','Lower Six','Further Vectors',5),
('Malaysia','Further Mathematics (T)','Lower Six','Mathematical Induction',6),

('Malaysia','Further Mathematics (T)','Upper Six','Further Differential Equations',1),
('Malaysia','Further Mathematics (T)','Upper Six','Numerical Methods',2),
('Malaysia','Further Mathematics (T)','Upper Six','Further Probability',3),
('Malaysia','Further Mathematics (T)','Upper Six','Further Statistics',4),
('Malaysia','Further Mathematics (T)','Upper Six','Group Theory Basics',5),
('Malaysia','Further Mathematics (T)','Upper Six','STPM Examination Preparation',6),

('Malaysia','History','Lower Six','Historiography and Source Skills',1),
('Malaysia','History','Lower Six','Nationalism in Southeast Asia',2),
('Malaysia','History','Lower Six','Colonialism and its Impact',3),
('Malaysia','History','Lower Six','Malaysia''s Path to Independence',4),
('Malaysia','History','Lower Six','Essay Writing Skills',5),
('Malaysia','History','Lower Six','Document-based Question Skills',6),

('Malaysia','History','Upper Six','Regional Cooperation in ASEAN',1),
('Malaysia','History','Upper Six','Malaysia in the Global Community',2),
('Malaysia','History','Upper Six','STPM Essay Practice',3),
('Malaysia','History','Upper Six','STPM DBQ Practice',4),
('Malaysia','History','Upper Six','Case Studies',5),
('Malaysia','History','Upper Six','Examination Strategies',6),

('Malaysia','Geography','Lower Six','Physical Geography Fundamentals',1),
('Malaysia','Geography','Lower Six','Climatic Systems',2),
('Malaysia','Geography','Lower Six','Geographical Skills',3),
('Malaysia','Geography','Lower Six','Fieldwork Techniques',4),
('Malaysia','Geography','Lower Six','Case Studies',5),
('Malaysia','Geography','Lower Six','Essay Writing Skills',6),

('Malaysia','Geography','Upper Six','Development Geography',1),
('Malaysia','Geography','Upper Six','Global Interactions',2),
('Malaysia','Geography','Upper Six','STPM Essay Practice',3),
('Malaysia','Geography','Upper Six','STPM Data Response Practice',4),
('Malaysia','Geography','Upper Six','Case Studies',5),
('Malaysia','Geography','Upper Six','Examination Strategies',6),

('Malaysia','Literature in English','Lower Six','Poetry Analysis',1),
('Malaysia','Literature in English','Lower Six','Prose Analysis',2),
('Malaysia','Literature in English','Lower Six','Drama Analysis',3),
('Malaysia','Literature in English','Lower Six','Literary Criticism Basics',4),
('Malaysia','Literature in English','Lower Six','Set Text Study',5),
('Malaysia','Literature in English','Lower Six','Essay Writing Skills',6),

('Malaysia','Literature in English','Upper Six','Comparative Analysis',1),
('Malaysia','Literature in English','Upper Six','Unseen Poetry Practice',2),
('Malaysia','Literature in English','Upper Six','Unseen Prose Practice',3),
('Malaysia','Literature in English','Upper Six','STPM Essay Practice',4),
('Malaysia','Literature in English','Upper Six','Set Text Revision',5),
('Malaysia','Literature in English','Upper Six','Examination Strategies',6),

('Malaysia','Accounting','Lower Six','Introduction to Accounting Principles',1),
('Malaysia','Accounting','Lower Six','Double Entry Bookkeeping',2),
('Malaysia','Accounting','Lower Six','Trial Balance and Adjustments',3),
('Malaysia','Accounting','Lower Six','Financial Statements',4),
('Malaysia','Accounting','Lower Six','Partnership Accounts',5),
('Malaysia','Accounting','Lower Six','Bank Reconciliation',6),

('Malaysia','Accounting','Upper Six','Company Accounts',1),
('Malaysia','Accounting','Upper Six','Ratio Analysis',2),
('Malaysia','Accounting','Upper Six','Cash Flow Statements',3),
('Malaysia','Accounting','Upper Six','Cost Accounting Basics',4),
('Malaysia','Accounting','Upper Six','Practice Questions',5),
('Malaysia','Accounting','Upper Six','STPM Examination Preparation',6),

('Malaysia','Business Studies','Lower Six','Introduction to Business Studies',1),
('Malaysia','Business Studies','Lower Six','Forms of Business Ownership',2),
('Malaysia','Business Studies','Lower Six','Business Planning',3),
('Malaysia','Business Studies','Lower Six','Marketing Concepts',4),
('Malaysia','Business Studies','Lower Six','Human Resource Management Basics',5),
('Malaysia','Business Studies','Lower Six','Business Ethics',6),

('Malaysia','Business Studies','Upper Six','Operations Management',1),
('Malaysia','Business Studies','Upper Six','Financial Management',2),
('Malaysia','Business Studies','Upper Six','Entrepreneurship',3),
('Malaysia','Business Studies','Upper Six','Business Growth Strategies',4),
('Malaysia','Business Studies','Upper Six','Practice Questions',5),
('Malaysia','Business Studies','Upper Six','STPM Examination Preparation',6);
